# Generated by Django 4.1.7 on 2023-03-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0004_livros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
    ]
