# Generated by Django 4.1.7 on 2023-03-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0005_alter_autor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name_plural': 'Livros'},
        ),
    ]
