# Generated by Django 4.1.7 on 2023-03-21 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0006_alter_livros_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='livraria.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='editora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='livraria.editora'),
            preserve_default=False,
        ),
    ]
